(()=>{'use strict';
// Fallback visual: el contenido no depende de IntersectionObserver para ser visible.
document.querySelectorAll('.reveal').forEach(x=>x.classList.add('visible'));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const progress=$('#progress');addEventListener('scroll',()=>{if(progress){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%'}},{passive:true});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(x=>observer.observe(x));
const menu=$('#menuBtn'),nav=$('#mainNav');menu?.addEventListener('click',()=>nav.style.display=nav.style.display==='flex'?'none':'flex');nav?.querySelectorAll('a').forEach(a=>a.onclick=()=>{if(innerWidth<901)nav.style.display='none'});
const parallax=$$('.hero-bg,.culture-bg,.challenge-bg,.finale-bg');addEventListener('scroll',()=>parallax.forEach((x,i)=>x.style.transform=`translateY(${scrollY*(i?-.018:-.035)}px) scale(1.05)`),{passive:true});

const locationData={choco:{name:'Chocó',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nuqui,%20Choc%C3%B3,%20Colombia.jpg',credit:'Foto: Dwayne Reilander · Wikimedia Commons · CC BY-SA 4.0'},valle:{name:'Valle del Cauca',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Buenaventura,%20Colombia.jpg',credit:'Foto: Roboting · Wikimedia Commons · CC BY-SA 4.0'},cauca:{name:'Cauca',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Guapi,%20Cauca,%20un%20destino%20en%20busca%20de%20un%20puerto.jpg',credit:'Foto: Angeles2023 · Wikimedia Commons · CC BY-SA 4.0'},narino:{name:'Nariño',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/TumacoBeach.jpg',credit:'Foto: Daniel Rosasssss · Wikimedia Commons · CC BY-SA 4.0'}};
const photo=$('.schematic-photo'),caption=photo?.parentElement?.querySelector('.schematic-caption span');const locationLabels={choco:'.schematic-label.l1',valle:'.schematic-label.l2',cauca:'.schematic-label.l3',narino:'.schematic-label.l4'};
function selectLocation(key){const item=locationData[key];if(!item||!photo)return;photo.classList.remove('location-change');void photo.offsetWidth;photo.style.backgroundImage=`linear-gradient(180deg,rgba(3,18,23,.02) 20%,rgba(3,18,23,.72) 100%),url(\"${item.image}\")`;photo.classList.add('location-change');photo.dataset.location=key;if(caption)caption.textContent=`${item.name} · ${item.credit}`;Object.entries(locationLabels).forEach(([k,selector])=>$(selector)?.classList.toggle('active',k===key))}
const locationStyle=document.createElement('style');locationStyle.textContent=`.schematic-photo{background-size:cover;background-position:center;transition:background-image .25s ease,transform .35s ease,filter .35s ease;overflow:hidden}.schematic-photo.location-change{animation:locationPulse .45s ease}@keyframes locationPulse{0%{opacity:.65;transform:scale(1.025)}100%{opacity:1;transform:scale(1)}}.schematic-label{cursor:pointer;transition:transform .2s ease,background .2s ease,border-color .2s ease;z-index:4}.schematic-label:hover,.schematic-label.active{transform:translateY(-2px) scale(1.05);background:rgba(91,230,190,.24);border-color:rgba(139,255,218,.7);box-shadow:0 8px 22px rgba(0,0,0,.22)}.schematic-caption span{display:block;max-width:90%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}`;document.head.appendChild(locationStyle);
Object.entries(locationLabels).forEach(([key,selector])=>{const el=$(selector);if(!el)return;el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Mostrar imagen real de ${locationData[key].name}`);el.addEventListener('click',()=>selectLocation(key));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectLocation(key)}})});

const data={
choco:['Chocó','El litoral chocoano combina selva húmeda tropical, ríos, manglares, playas, estuarios y serranías. El Parque Nacional Natural Utría se encuentra en este departamento y protege una combinación especialmente diversa de ambientes marino-costeros. La costa chocoana también es un corredor para especies migratorias como la yubarta y varias tortugas marinas.'],
valle:['Valle del Cauca','El Pacífico del Valle del Cauca tiene como principal referente costero a Buenaventura. El territorio reúne manglares, esteros, playas, selva y ambientes marinos, y cuenta con áreas protegidas como Uramba Bahía Málaga. La actividad portuaria de Buenaventura es un componente importante de la conectividad económica del litoral.'],
cauca:['Cauca','El litoral caucano incluye municipios como Guapi, Timbiquí y López de Micay. Sus ríos, esteros, manglares, selvas y costa sostienen actividades como pesca, agricultura y turismo de naturaleza. En el departamento se encuentra el Parque Nacional Natural Gorgona, con ecosistemas terrestres y marinos.'],
narino:['Nariño','El Pacífico nariñense incluye Tumaco, Cabo Manglares y una extensa red de esteros y manglares. El Parque Nacional Natural Sanquianga protege una gran extensión de manglar y sus comunidades mantienen una relación histórica con la pesca y la recolección de piangua.'],
relieve:['Serranía del Baudó','El relieve del Pacífico combina llanuras costeras, valles fluviales, colinas y serranías. La serranía del Baudó acompaña buena parte del Pacífico norte y sus pendientes se encuentran muy cerca de ambientes de selva y mar. En Utría, por ejemplo, las elevaciones cubiertas de bosque llegan hasta la costa.'],
rios:['Ríos que conectan','El agua es una de las claves del territorio. Entre los ríos destacados se encuentran Atrato, San Juan, Baudó, Mira y Patía. Además de aportar agua y nutrientes, los ríos y esteros funcionan como corredores de movilidad y comunicación para muchas comunidades del litoral.'],
clima:['Un mundo húmedo','El Pacífico colombiano presenta precipitaciones muy abundantes y alta humedad. Estas condiciones favorecen bosques tropicales densos, redes de ríos y ecosistemas costeros productivos. La lluvia también influye en la movilidad, la agricultura, la pesca y la conservación del suelo.'],
selva:['Selva húmeda tropical','La selva húmeda tropical es uno de los grandes ecosistemas del Pacífico. Su estructura vegetal ofrece alimento, refugio y corredores para una enorme variedad de organismos. También ayuda a regular el agua y almacena carbono. En Utría y Gorgona la selva se encuentra estrechamente relacionada con el litoral y otros ecosistemas.'],
manglar:['Manglares','Los manglares ocupan zonas donde interactúan el agua marina, los esteros y el continente. Sus raíces sirven de refugio y crianza para peces, crustáceos y otros organismos. También protegen sectores de la costa y tienen una relación directa con actividades como la pesca y la recolección de piangua.'],
estuario:['Estuarios y esteros','En los estuarios se mezclan procesos de agua dulce y agua marina. Son ambientes dinámicos donde cambian salinidad, profundidad y circulación con las mareas. En el Pacífico forman redes de canales y esteros que conectan manglares, ríos, comunidades y zonas de pesca.'],
arrecife:['Arrecifes coralinos','Los arrecifes son ecosistemas marinos que ofrecen refugio y zonas de alimentación a numerosos organismos. En Gorgona y Utría existen formaciones coralinas asociadas a una alta diversidad marina. Su conservación depende de mantener la calidad del agua y reducir las presiones sobre la costa.'],
playa:['Playas y litoral','Las playas forman parte de la franja costera y cumplen funciones ecológicas además de ser espacios de uso comunitario y turístico. Algunas son utilizadas por tortugas marinas para la reproducción. Su dinámica cambia con mareas, oleaje, corrientes y aporte de sedimentos.'],
yubarta:['Yubarta o ballena jorobada','Las ballenas jorobadas llegan cada año a las aguas cálidas del Pacífico colombiano durante su migración. El Ministerio de Ambiente señala que la temporada suele concentrarse entre julio y noviembre. Las aguas costeras son importantes para reproducción y crianza, por lo que el tránsito responsable de embarcaciones es parte de la conservación.'],
tortugas:['Tortugas marinas','Las aguas y playas del Pacífico sirven como zonas de alimentación, refugio y reproducción para tortugas marinas. Utría, por ejemplo, protege playas donde llegan especies a desovar. La conservación requiere cuidar tanto la arena y vegetación costera como los ambientes marinos cercanos.'],
aves:['Aves del Pacífico','La combinación de selva, ríos, manglares, playas y litoral crea muchos hábitats para aves. Algunas especies son residentes y otras utilizan la costa durante sus desplazamientos. Los humedales y manglares son especialmente importantes como lugares de alimentación y refugio.'],
corales:['Arrecifes y fauna marina','Los arrecifes coralinos forman estructuras que sirven de refugio a peces, moluscos, crustáceos y otros organismos. En Gorgona se han documentado comunidades coralinas junto a una amplia diversidad marina. La protección de estos ambientes ayuda a conservar cadenas ecológicas completas.'],
territorio:['Comunidades y territorio','La geografía humana del Pacífico está marcada por la relación cotidiana con ríos, esteros, selva y litoral. En muchos lugares el transporte fluvial y marítimo es fundamental. La alimentación, los oficios, la vivienda, la música y las celebraciones también están vinculados con los recursos y paisajes locales.'],
oralidad:['Tradición oral','La tradición oral conserva historias, conocimientos, cantos, relatos y formas de interpretar el territorio. La transmisión entre generaciones permite mantener memoria colectiva y prácticas culturales. En el Pacífico, la palabra y la música tienen un papel importante en la vida comunitaria.'],
diversidad:['Diversidad cultural','El Pacífico colombiano tiene una fuerte presencia de comunidades afrocolombianas y pueblos indígenas, además de otras poblaciones locales. Sus conocimientos sobre navegación, pesca, plantas, cocina, música y manejo del territorio forman parte del patrimonio vivo de la región.'],
currulao:['Currulao','El currulao es una expresión musical emblemática del Pacífico Sur. Se relaciona con la marimba de chonta, los cununos, los bombos, los guasás y las voces. Además de música, es una práctica social que acompaña baile, encuentro y transmisión de conocimientos.'],
arrullo:['Arrullo','El arrullo integra canto y participación comunitaria y forma parte de las expresiones tradicionales del Pacífico Sur. Su práctica está vinculada a espacios de encuentro, memoria y transmisión cultural.'],
alabao:['Alabao','El alabao es una expresión vocal tradicional relacionada con la memoria y con prácticas comunitarias. Sus cantos pueden acompañar momentos colectivos y conservar conocimientos transmitidos entre generaciones.'],
juga:['Juga','La juga hace parte del repertorio de músicas y cantos tradicionales del Pacífico Sur. Sus interpretaciones combinan voces, instrumentos de percusión y marimba dentro de contextos festivos y comunitarios.'],
agricultura:['Agricultura','La agricultura es una actividad económica importante para numerosas comunidades. Los cultivos y huertas locales aportan alimentos y medios de vida, y se relacionan con las condiciones de lluvia, suelos, ríos y acceso al territorio.'],
pesca:['Pesca','La pesca artesanal y comercial está directamente vinculada con ríos, esteros y mar. Además del pescado, existen actividades de recolección de moluscos como la piangua en zonas de manglar. La conservación de los ecosistemas acuáticos es fundamental para mantener esta actividad.'],
'mineria-economia':['Minería','La minería forma parte de la historia económica de distintos territorios del Pacífico, especialmente alrededor de depósitos de oro. Su importancia económica debe analizarse junto con los impactos que pueden producir prácticas no controladas sobre ríos, suelos, bosques y comunidades.'],
puertos:['Actividad portuaria','Buenaventura es el principal referente portuario del litoral Pacífico colombiano. El movimiento de mercancías y servicios portuarios conecta el territorio con redes nacionales e internacionales. Esta actividad convive con comunidades pesqueras y con ecosistemas costeros que requieren manejo responsable.'],
turismo:['Turismo de naturaleza y cultura','El Pacífico ofrece selvas, manglares, playas, avistamiento de fauna, gastronomía y expresiones culturales. Utría, Gorgona, Uramba Bahía Málaga y otros lugares protegidos reciben actividades de turismo de naturaleza. La planificación debe priorizar conservación, seguridad y participación comunitaria.'],
forestal:['Recursos forestales','Los bosques aportan madera, frutos, fibras, plantas y otros recursos que pueden tener usos locales. El reto está en diferenciar el aprovechamiento responsable de la extracción que deteriora el bosque. La restauración y el manejo comunitario son herramientas importantes para conservar estos recursos.'],
utria:['Parque Nacional Natural Utría','Utría está en Chocó y protege selva húmeda tropical, manglares, playas, litorales rocosos, arrecifes y ambientes marinos. Parques Nacionales registra allí especies migratorias como tortugas, aves y ballenas. También destaca la relación del área con comunidades afrocolombianas e indígenas.'],
gorgona:['Parque Nacional Natural Gorgona','Gorgona pertenece al departamento del Cauca y reúne selva húmeda tropical, manglares, playas arenosas, litoral rocoso y arrecifes coralinos. Parques Nacionales registra una amplia diversidad terrestre y marina y señala la importancia de la participación de comunidades pesqueras en procesos de conservación.'],
malaga:['Uramba Bahía Málaga','Uramba Bahía Málaga se encuentra en el litoral del Valle del Cauca y protege ambientes marino-costeros, manglares, esteros y playas. Es también un territorio donde comunidades locales participan en actividades productivas y de conservación. Las ballenas jorobadas llegan a sus aguas durante la temporada migratoria.'],
'manglares-sur':['Cabo Manglares','Cabo Manglares se ubica en el extremo sur del Pacífico nariñense. Su paisaje está marcado por manglares, esteros, playas y una gran dinámica de agua. Es un territorio importante para biodiversidad y para comunidades cuya vida cotidiana depende de los recursos costeros.'],
deforestacion:['Deforestación','La pérdida de bosque reduce hábitats, altera ciclos del agua y puede afectar suelos y actividades que dependen de la selva. En el Pacífico el análisis debe considerar causas diferentes según el territorio, así como las acciones de conservación y restauración que realizan comunidades e instituciones.'],
mineria:['Minería ilegal','La extracción no autorizada puede generar alteraciones en ríos, sedimentos y cobertura vegetal. También puede afectar actividades como pesca y agricultura. El análisis responsable debe distinguir entre minería formal, minería artesanal y explotación ilegal y revisar datos específicos del territorio estudiado.'],
desigualdad:['Desigualdad y acceso','Los indicadores regionales muestran brechas en servicios, conectividad, educación, salud, vivienda e ingresos. Estas diferencias no son iguales en los cuatro departamentos, por lo que conviene estudiar los datos por departamento y por zonas urbanas y rurales en lugar de tratar al Pacífico como un territorio uniforme.'],
presion:['Presión sobre ecosistemas','Los ecosistemas costeros y terrestres reciben presiones relacionadas con contaminación, extracción de recursos, cambios de uso del suelo, sobreexplotación y cambio climático. La conservación requiere combinar ciencia, educación ambiental, gestión pública y conocimiento de las comunidades.']
};
const modal=$('#modal'),title=$('#modalTitle'),body=$('#modalBody');function openInfo(k){const d=data[k];if(!d)return;if(title)title.textContent=d[0];if(body)body.innerHTML=`<p>${d[1]}</p><p><b>Para investigar:</b> identifica el lugar, el ecosistema o la actividad mencionada y contrasta el dato con una fuente institucional.</p>`;modal?.classList.add('show');modal?.setAttribute('aria-hidden','false')}
$$('[data-info]').forEach(x=>x.addEventListener('click',()=>{if(locationData[x.dataset.info])selectLocation(x.dataset.info);openInfo(x.dataset.info)}));$('#modalClose')?.addEventListener('click',()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')});modal?.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}});addEventListener('keydown',e=>{if(e.key==='Escape'){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true')}});selectLocation('choco');

let audio=null,master=null,amb=false;function audioStart(){if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.001;master.connect(audio.destination);const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=82;g.gain.value=.11;o.connect(g).connect(master);o.start();const l=audio.createOscillator(),lg=audio.createGain();l.frequency.value=.08;lg.gain.value=25;l.connect(lg).connect(o.frequency);l.start()}if(audio.state==='suspended')audio.resume();amb=!amb;master.gain.setTargetAtTime(amb?.05:.001,audio.currentTime,.25);if($('#soundBtn'))$('#soundBtn').textContent=amb?'◉ Ambiente activo':'◉ Activar ambiente'}$('#soundBtn')?.addEventListener('click',audioStart);$('#marimbaBtn')?.addEventListener('click',()=>{if(!audio)audioStart();const notes=[261.63,329.63,392,523.25,392,329.63,293.66,349.23];notes.forEach((f,i)=>setTimeout(()=>{const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.09,audio.currentTime+.025);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.5);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+.55)},i*230))});

$$('.game-tabs button').forEach(b=>b.onclick=()=>{$$('.game-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.game-panel').forEach(x=>x.classList.remove('active'));$('#game'+b.dataset.game[0].toUpperCase()+b.dataset.game.slice(1))?.classList.add('active')});
const qs=[
['¿Qué cuatro departamentos forman la agrupación Pacífica usada por el DANE?',['Cauca, Chocó, Nariño y Valle del Cauca','Cauca, Chocó y Nariño','Chocó, Nariño y Valle del Cauca','Cauca, Nariño y Valle del Cauca'],0],
['¿Cuál de estos ríos es destacado en el Pacífico colombiano?',['Atrato','San Juan','Baudó','Mira'],0],
['¿Qué instrumento da nombre a una de las principales tradiciones musicales del Pacífico Sur?',['Marimba de chonta','Cununo','Bombo','Guasá'],0],
['¿Qué ecosistema se encuentra en el Parque Nacional Natural Gorgona?',['Arrecifes coralinos','Manglares','Selva húmeda tropical','Todos los anteriores'],3],
['¿En qué época suele llegar la yubarta a las aguas cálidas del Pacífico colombiano?',['Entre julio y noviembre','Entre agosto y octubre','Entre junio y septiembre','Entre septiembre y diciembre'],0],
['¿Cuál de estos lugares está en Chocó?',['Parque Nacional Natural Utría','Nuquí','Bahía Solano','Todos los anteriores'],3],
['¿Qué actividad está directamente relacionada con los esteros y el mar?',['Pesca','Navegación local','Recolección de piangua','Todas las anteriores'],3],
['¿Qué práctica ayuda a investigar responsablemente el Pacífico?',['Contrastar fuentes institucionales','Registrar la fecha de los datos','Relacionar el dato con un lugar concreto','Todas las anteriores'],3],
['¿Qué caracteriza a los manglares del Pacífico?',['Son ecosistemas de transición entre tierra y mar','Sirven como refugio y crianza para organismos','Están vinculados con pesca y recolección','Todas las anteriores'],3],
['¿Qué expresión pertenece al patrimonio musical del Pacífico Sur?',['Currulao','Arrullo','Alabao','Todas las anteriores'],3]
];
let qi=0,score=0,answered=false;const qText=$('#qText'),qOptions=$('#qOptions'),qFeedback=$('#qFeedback'),next=$('#nextQ');function resetQuiz(){qi=0;score=0;if(next){next.textContent='Siguiente →';next.classList.add('hidden');next.onclick=advanceQuiz}renderQ()}function renderQ(){const q=qs[qi];answered=false;if($('#qCount'))$('#qCount').textContent=`Pregunta ${qi+1} / ${qs.length}`;if($('#qScore'))$('#qScore').textContent=`Puntos: ${score}`;if($('#qBar'))$('#qBar').style.width=`${(qi+1)/qs.length*100}%`;if(qText)qText.textContent=q[0];if(qOptions)qOptions.innerHTML='';if(qFeedback)qFeedback.textContent='';next?.classList.add('hidden');q[1].forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>{if(answered)return;answered=true;qOptions.querySelectorAll('button').forEach((x,j)=>{x.disabled=true;if(j===q[2])x.classList.add('correct');if(j===i&&i!==q[2])x.classList.add('wrong')});if(i===q[2]){score++;qFeedback.textContent='✓ Correcto. Este dato pertenece al territorio del Pacífico.'}else qFeedback.textContent='✦ Revisa la respuesta correcta y vuelve a explorar la sección relacionada.';if($('#qScore'))$('#qScore').textContent=`Puntos: ${score}`;next?.classList.remove('hidden')};qOptions?.appendChild(b)})}function advanceQuiz(){if(qi<qs.length-1){qi++;renderQ()}else{if(qText)qText.textContent=`Resultado: ${score} / ${qs.length}`;if(qOptions)qOptions.innerHTML='';if(qFeedback)qFeedback.textContent=score>=7?'¡Recorrido completado!':'Buen comienzo: vuelve a explorar el contenido del Pacífico y prueba otra vez.';next.textContent='Repetir';next.classList.remove('hidden');next.onclick=resetQuiz}}next?.addEventListener('click',advanceQuiz);renderQ();

const symbols=['🐋','🌿','🎶','🌊','🐋','🌿','🎶','🌊'];let first=null,lock=false,found=0,moves=0;function memory(){const board=$('#memoryBoard');if(!board)return;board.innerHTML='';first=null;lock=false;found=0;moves=0;if($('#memoryMoves'))$('#memoryMoves').textContent='Movimientos: 0';symbols.slice().sort(()=>Math.random()-.5).forEach(s=>{const b=document.createElement('button');b.className='memory-card';b.textContent='?';b.dataset.symbol=s;b.onclick=()=>{if(lock||b===first||b.classList.contains('flipped'))return;b.classList.add('flipped');b.textContent=s;if(!first){first=b;return}moves++;if($('#memoryMoves'))$('#memoryMoves').textContent=`Movimientos: ${moves}`;if(first.dataset.symbol===b.dataset.symbol){found+=2;first=null;if(found===symbols.length&&$('#memoryMoves'))$('#memoryMoves').textContent=`¡Completado en ${moves} movimientos!`}else{lock=true;setTimeout(()=>{first?.classList.remove('flipped');if(first)first.textContent='?';b.classList.remove('flipped');b.textContent='?';first=null;lock=false},650)}};board.appendChild(b)})}$('#memoryReset')?.addEventListener('click',memory);memory();
let rs=0;const steps=[['¿Dónde nace el río?','⛰️ En zonas altas o nacientes'],['¿Por dónde continúa?','🌿 Por su cauce y ecosistemas ribereños'],['¿Qué conecta?','🏘️ Comunidades y territorios'],['¿Dónde termina?','🌊 En su desembocadura']];function river(){const box=$('#riverChoices');if(!box)return;box.innerHTML='';if(rs===steps.length){if($('#riverResult'))$('#riverResult').textContent='✓ Ruta completada. Has seguido el agua desde su nacimiento hasta el mar.';return}if($('#riverResult'))$('#riverResult').textContent=steps[rs][0];const opts=[steps[rs][1],'🌊 Un estero conectado con el sistema hídrico','🌿 Un manglar relacionado con el cauce'];opts.sort(()=>Math.random()-.5).forEach(o=>{const b=document.createElement('button');b.className='river-choice';b.textContent=o;b.onclick=()=>{if(o===steps[rs][1]){rs++;river()}else if($('#riverResult'))$('#riverResult').textContent='✦ Piensa en el recorrido natural del agua y vuelve a elegir.'};box.appendChild(b)})}river();

async function initPdfSlideshow(){
  const viewer=document.querySelector('#pdfSlideshow');
  if(!viewer)return;
  const canvas=document.querySelector('#pdfCanvas');
  const ctx=canvas?.getContext('2d');
  const loading=document.querySelector('#pdfLoading');
  const info=document.querySelector('#pdfPageInfo');
  const prev=document.querySelector('#pdfPrev');
  const next=document.querySelector('#pdfNext');
  if(!canvas||!ctx)return;
  try{
    const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.149/pdf.min.mjs');
    pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.149/pdf.worker.min.mjs';
    const pdf=await pdfjs.getDocument('The_Pacific_Paradox.pdf').promise;
    let pageNumber=1;
    async function renderPage(){
      if(loading)loading.hidden=false;
      const page=await pdf.getPage(pageNumber);
      const base=page.getViewport({scale:1});
      const maxWidth=Math.min(viewer.clientWidth-36,1100);
      const scale=Math.max(.5,Math.min(1.8,maxWidth/base.width));
      const viewport=page.getViewport({scale});
      canvas.width=Math.floor(viewport.width);
      canvas.height=Math.floor(viewport.height);
      await page.render({canvasContext:ctx,viewport}).promise;
      if(info)info.textContent=`Diapositiva ${pageNumber} / ${pdf.numPages}`;
      if(prev)prev.disabled=pageNumber<=1;
      if(next)next.disabled=pageNumber>=pdf.numPages;
      if(loading)loading.hidden=true;
    }
    prev?.addEventListener('click',()=>{if(pageNumber>1){pageNumber--;renderPage()}});
    next?.addEventListener('click',()=>{if(pageNumber<pdf.numPages){pageNumber++;renderPage()}});
    addEventListener('resize',()=>renderPage(),{passive:true});
    addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&pageNumber>1){pageNumber--;renderPage()}if(e.key==='ArrowRight'&&pageNumber<pdf.numPages){pageNumber++;renderPage()}});
    renderPage();
  }catch(error){
    if(loading){loading.hidden=false;loading.textContent='No se pudo cargar la presentación. Puedes descargar el PDF debajo.'}
    console.error('PDF slideshow:',error);
  }
}
initPdfSlideshow();
})();